### PR TITLE
Support darwin-arm64

### PR DESCRIPTION
**Pull request by joelanford**
Update `g` to correctly handle parsing `uname -m` on Mac M1 machines.

### CODE REVIEW

**Comment by stefanmaric** [comment]
Hi @joelanford 

Thanks for bringing this. :heart: 

I don't have an M1 chip at hand, but I've read that `uname` (or whatever uses the underlying syscall) will return `x86_64` depending on whenever Terminal or the actual shell is ran with Rosetta or not.

For a matter of completeness, I'm going to ask you: how does your actual go development flow look like on an M1? — so a note can be added to the `README` for anyone with an M1 mac.

See: https://stackoverflow.com/questions/65346260/get-real-architecture-of-m1-mac-regardless-of-rosetta
See: https://vineethbharadwaj.medium.com/m1-mac-switching-terminal-between-x86-64-and-arm64-e45f324184d9
See: https://stackoverflow.com/questions/65457674/unexpected-output-of-arch-on-osx-using-mac-m1-installing-elastic-beans

**Comment by stefanmaric** [comment]
@joelanford in the meantime, I [pushed some changes](https://github.com/stefanmaric/g/releases/tag/0.8.1) so will also need you to rebase your branch so it gets the latest and the new CI pipeline runs before we can merge this PR.

**Comment by joelanford** [comment]
None of my development is under Rosetta. Go 1.16 supports the M1 chip natively, as do the IDEs I use (Goland, Vim, and vscode).

I have been unable to get any terminal or shell to return anything other than `arm64`, and in all cases running `go version` always succeeds and returns `darwin/arm64`.
```console
$ env /usr/bin/arch -x86_64 /bin/zsh --login
$ uname -m
arm64
$ go version
go version go1.16.2 darwin/arm64
```

If it matters, I'm on macOS 11.2.3.

**Comment by stefanmaric** [comment]
Interesting. I thought one had to have some consideration of the arch but, based on your snipped, it seems transparent.

Thanks for your help @joelanford :heart:

**Pull request merged**
